IN-3116: dotNET Example QR
getyoti/yoti-dotnet-sdk pull request #239
Opened 2020-09-21 15:45 UTC by nikhilPank

2020-09-22 09:23 UTC, echarrod requested changes
We'll need to update the .NET Core Example as well, right?

2020-09-22 10:39 UTC, davidgrayston requested changes
Do we need to update the dynamic share example too?

https://github.com/getyoti/yoti-dotnet-sdk/blob/development/src/Examples/Profile/47Example/Views/Home/DynamicScenario.cshtml#L77

2020-09-24 15:40 UTC, echarrod approved these changes

2020-09-24 16:08 UTC, davidgrayston approved these changes

2020-09-25 14:36 UTC, merged