SDK-2374 added failure reason info to idv and added tests
getyoti/yoti-dotnet-sdk pull request #466
Opened 2024-06-25 21:12 UTC by mehmet-yoti

2024-06-26 11:26 UTC, saurabh-yoti requested changes

2024-06-26 11:26 UTC, saurabh-yoti commented on src/Yoti.Auth/DocScan/Session/Retrieve/IdentityProfile/RequirementNotMetDetails.cs
Properties are already public and have getters. So, separate Get methods like `GetFailureType()` and `GetDetails()` are not required.

2024-06-26 11:26 UTC, saurabh-yoti commented on test/Yoti.Auth.Tests/DocScan/Session/Retrieve/IdentityProfile/FailureReasonResponseTest.cs
Please update the test after removing redundant Get methods in `RequirementNotMetDetails.cs`.

2024-06-26 15:59 UTC, mehmet-yoti commented on src/Yoti.Auth/DocScan/Session/Retrieve/IdentityProfile/RequirementNotMetDetails.cs
solved

2024-06-26 15:59 UTC, mehmet-yoti commented on test/Yoti.Auth.Tests/DocScan/Session/Retrieve/IdentityProfile/FailureReasonResponseTest.cs
solved

2024-06-28 08:56 UTC, saurabh-yoti approved these changes

2024-06-28 09:59 UTC, merged